name: CI

on:
  push:
    branches: [main]
    paths:
      - 'api/**'
  push:
    branches: [main]
    paths:
      - 'app/**'
  pull_request:
    branches: [main]

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run build --if-present
    - name: test
      run: npm test
    - name: lint
      run: npm run lint

  build-app:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run build --if-present
    - name: test
      run: npm test
    - name: lint
      run: npm run lint
